### DISCUSSION TITLE
Controlling i3 Workspaces with an External USB Numpad

### DISCUSSION THREAD

**Discussion by djarum-black** [i3/i3#6049] [Show and tell]
**Title:** Controlling i3 Workspaces and Executing Shell Commands with an External USB Numpad

---

Hello everyone,

I've been working on a Python script that allows me to use an external generic USB numpad to control various functions in i3 and execute shell commands. I thought I'd share it here in case anyone else finds it useful.

It's configured using a YAML file, which maps keys on the numpad to commands or functions.

You also have the ability to set window-specific shortcuts. These are only activated when a specific window is in focus. The window matching can be done based on the start, end, or any part of the window name, or an exact match.

Here's an example of the configuration file `shortcuts.yaml`:

```yaml
device: '/dev/input/event2'
KEY_KP1:
  - command: ['i3-msg', 'workspace', 'NP1']
KEY_KP2:
  - command: ['i3-msg', 'workspace', 'NP2']
KEY_KP3:
  - command: ['i3-msg', 'workspace', 'NP3']
KEY_KP4:
  - command: ['i3-msg', 'workspace', 'NP4']
KEY_KP5:
  - command: ['i3-msg', 'workspace', 'NP5']
KEY_KP6:
  - command: ['i3-msg', 'workspace', 'NP6']
KEY_KP7:
  - command: ['i3-msg', 'workspace', 'NP7']
KEY_KP8:
  - command: ['i3-msg', 'workspace', 'NP8']
KEY_KP9:
  - command: ['i3-msg', 'workspace', 'NP9']
KEY_KP0:
  - command: ['i3-msg', 'workspace', 'NP10']
KEY_KPMINUS:
  - command: ['xdotool', 'key', 'Shift+Ctrl+a']
    ifwindow: 'Terminal'
    match_type: 'start'
  - command: ['xdotool', 'key', 'Shift+a']
    ifwindow: 'Firefox'
    match_type: 'end'
  - command: ['xdotool', 'key', 'Shift+b']
    ifwindow: 'Browser'
    match_type: 'contain'
```

In this example, pressing the keys from `KEY_KP1` to `KEY_KP9` and `KEY_KP0` on the numpad will switch to workspaces 1 to 10 respectively. The `KEY_KPMINUS` key will perform different actions based on the active window's name.

 You can run any command that can be executed in a shell. The command just needs to be specified as a list of strings, where each string is a part of the command. For example, if you want to run the command `ls -l`, you would add it to the `shortcuts.yaml` file like this:

```yaml
KEY_KPPLUS:
  - command: ['ls', '-l']
```

In this case, when you press the `KEY_KPPLUS` key on your numpad, the `ls -l` command will be executed. The output of the command will be displayed in the terminal where you are running the `numpad.py` script.

To run the script, you'll need to install the required Python packages. You can do this by running `pip install -r requirements.txt` in your terminal. Then, simply run the script with `python numpad.py`.

You can find the Python script and the configuration file in my [GitHub Gist](https://gist.github.com/djarum-black/dc44420385f7d8b9408b007f549dd6d2).

I hope someone finds this useful.
