### DISCUSSION TITLE
i3 wallpapaper manager: define wallpaper for each workspace

### DISCUSSION THREAD

**Discussion by simmstein** [i3/i3#6187] [Show and tell]
Hello!

[i3 wallpaper manager](https://gitnet.fr/deblan/i3-wallpaper-manager) is a command-line tool designed to change the wallpaper depending of active workspaces on i3. The project is written in golang and the configuration file is in YAML. It uses IPC to detect workspace changes. It is open-source and I also provide binaries and Debian packages. It runs on amd64 and arm64 architectures.

Hope you like it!

**Comment by yusufaktepe** [comment]
Hi @simmstein, thanks for sharing this tool.

Is it possible to make the wallpaper utility configurable for those who don't want to use feh?

**Reply by simmstein** [reply]
Hi, 

What could be the configuration format?

**Reply by yusufaktepe** [reply]
Maybe read the command from `config.yaml`, is that possible? Like:
```yaml
wallpaper_tool: "xwallpaper --stretch"
default: /home/alice/wallpapers/default.jpg
workspaces:
...
```
