### ISSUE TITLE
'No usable outputs available' when starting a remote i3 session using X2Go

### ISSUE THREAD

**Issue by EmteZogaf** [i3/i3#2011]
I have a problem using i3 with x2go:
I'm on Arch Linux and sometimes working from home via X2Go. I let X2Go start i3 by calling a tiny bash script which sets the locale and calls `/usr/bin/i3`. All worked fine for months before but today, about 1 week after the last usage and some distro updates in between (I don't know exactly what has been all updated, but I can try to find out), it immediately quits the X2Go session and i3 reports `i3: No usable outputs available.`. 
For debugging I placed a call to `xrandr --verbose` at the top of the bash script which outputs:
```
xrandr: Failed to get size of gamma for output default
Screen 0: minimum 320 x 240, current 1366 x 768, maximum 1920 x 1200
default connected 1366x768+0+0 (0xa0) normal (normal) 0mm x 0mm
        Identifier: 0x8d
        Timestamp:  2096739596
        Subpixel:   unknown
        Clones:
        CRTC:       0
        CRTCs:      0
        Transform:  1.000000 0.000000 0.000000
                    0.000000 1.000000 0.000000
                    0.000000 0.000000 1.000000
                   filter:
  800x480 (0x8e) 23.040MHz
        h: width   800 start    0 end    0 total  800 skew    0 clock  28.80KHz
        v: height  480 start    0 end    0 total  480           clock  60.00Hz
  320x240 (0x8f)  4.608MHz
        h: width   320 start    0 end    0 total  320 skew    0 clock  14.40KHz
        v: height  240 start    0 end    0 total  240           clock  60.00Hz
[...]
```
Enabling the debug output of i3 via `-d all` I get this output (removed config file parsing, if wanted I can attach the full log file here):
```
19.10.2015 00:02:34 - main.c:main:491 - root_depth = 24, visual_id = 0x0000005c.
19.10.2015 00:02:34 - main.c:main:494 - root_screen->height_in_pixels = 768, root_screen->height_in_millimeters = 203, dpi = 96
19.10.2015 00:02:34 - main.c:main:495 - One logical pixel corresponds to 1 physical pixels on this display.
[...]
19.10.2015 00:02:34 - main.c:main:533 - root geometry reply: (0, 0) 1366 x 768
19.10.2015 00:02:34 - main.c:main:549 - initializing xcb-xkb
[...]
19.10.2015 00:02:34 - con.c:con_new_skeleton:52 - opening window
19.10.2015 00:02:34 - x.c:x_con_init:164 - Adding window 0x00400063 to lists
19.10.2015 00:02:34 - x.c:x_con_init:168 - adding new state for window id 0x00400063
19.10.2015 00:02:34 - con.c:con_new_skeleton:52 - opening window
19.10.2015 00:02:34 - x.c:x_con_init:164 - Adding window 0x00400064 to lists
19.10.2015 00:02:34 - x.c:x_con_init:168 - adding new state for window id 0x00400064
19.10.2015 00:02:34 - tree.c:_create___i3:41 - adding main content container
19.10.2015 00:02:34 - con.c:con_new_skeleton:52 - opening window
19.10.2015 00:02:34 - x.c:x_con_init:164 - Adding window 0x00400065 to lists
19.10.2015 00:02:34 - x.c:x_con_init:168 - adding new state for window id 0x00400065
19.10.2015 00:02:34 - con.c:con_new_skeleton:52 - opening window
19.10.2015 00:02:34 - x.c:x_con_init:164 - Adding window 0x00400066 to lists
19.10.2015 00:02:34 - x.c:x_con_init:168 - adding new state for window id 0x00400066
19.10.2015 00:02:34 - con.c:_con_attach:84 - it's a workspace. num = -1
19.10.2015 00:02:34 - main.c:main:641 - Checking for XRandR...
19.10.2015 00:02:34 - ERROR: Could not get RandR primary output
19.10.2015 00:02:34 - scratchpad.c:scratchpad_fix_resolution:253 - Current resolution: (0, 0) 1280 x 1024
19.10.2015 00:02:34 - scratchpad.c:scratchpad_fix_resolution:275 - new width = -1, new height = -1
19.10.2015 00:02:34 - scratchpad.c:scratchpad_fix_resolution:286 - Fixing coordinates of scratchpad windows
19.10.2015 00:02:34 - main.c:main:652 - Pointer at 496, 389
19.10.2015 00:02:34 - ERROR: ERROR: No screen at (496, 389), starting on the first screen
i3: No usable outputs available.
```
Starting an XFCE session by X2Go still works fine.

```
i3 version 4.11 (2015-09-30, branch "4.11")
X.Org X Server 1.17.2
x2goserver: 4.0.1.19
x2goagent: 3.5.0.32
xrandr program version 1.4.3
```
